/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Auth Service API
 * This is the authentication service for ChatOrbit.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  MainErrorResponse,
  MainLoginRequest,
  MainLoginResponse
} from './';






/**
 * Login a user with email and password
 * @summary Login
 */
export const postLogin = (
    mainLoginRequest: MainLoginRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MainLoginResponse>> => {
    
    
    return axios.default.post(
      `/login`,
      mainLoginRequest,options
    );
  }



export const getPostLoginMutationOptions = <TError = AxiosError<MainErrorResponse | MainErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLogin>>, TError,{data: MainLoginRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postLogin>>, TError,{data: MainLoginRequest}, TContext> => {

const mutationKey = ['postLogin'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLogin>>, {data: MainLoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  postLogin(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postLogin>>>
    export type PostLoginMutationBody = MainLoginRequest
    export type PostLoginMutationError = AxiosError<MainErrorResponse | MainErrorResponse>

    /**
 * @summary Login
 */
export const usePostLogin = <TError = AxiosError<MainErrorResponse | MainErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLogin>>, TError,{data: MainLoginRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postLogin>>,
        TError,
        {data: MainLoginRequest},
        TContext
      > => {

      const mutationOptions = getPostLoginMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    