/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Auth Service API
 * This is the authentication service for ChatOrbit.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  MainErrorResponse,
  MainMessageResponse,
  MainRegisterRequest
} from './';






/**
 * Register a new user with email, username, and password
 * @summary Register a new user
 */
export const postRegister = (
    mainRegisterRequest: MainRegisterRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MainMessageResponse>> => {
    
    
    return axios.default.post(
      `/register`,
      mainRegisterRequest,options
    );
  }



export const getPostRegisterMutationOptions = <TError = AxiosError<MainErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRegister>>, TError,{data: MainRegisterRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postRegister>>, TError,{data: MainRegisterRequest}, TContext> => {

const mutationKey = ['postRegister'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postRegister>>, {data: MainRegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  postRegister(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postRegister>>>
    export type PostRegisterMutationBody = MainRegisterRequest
    export type PostRegisterMutationError = AxiosError<MainErrorResponse>

    /**
 * @summary Register a new user
 */
export const usePostRegister = <TError = AxiosError<MainErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRegister>>, TError,{data: MainRegisterRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postRegister>>,
        TError,
        {data: MainRegisterRequest},
        TContext
      > => {

      const mutationOptions = getPostRegisterMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    