/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Auth Service API
 * This is the authentication service for ChatOrbit.
 * OpenAPI spec version: 1.0
 */

export interface MainRegisterRequest {
  email: string;
  /** @minLength 6 */
  password: string;
  /**
   * @minLength 2
   * @maxLength 100
   */
  username: string;
}
