/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Auth Service API
 * This is the authentication service for ChatOrbit.
 * OpenAPI spec version: 1.0
 */

export interface MainChangePasswordRequest {
  /** @minLength 6 */
  new_password: string;
  /** @minLength 6 */
  old_password: string;
}
